USE HUSKYHAPPENINGS;

CREATE TABLE COMMENT (
    COMMENTID INT AUTO_INCREMENT PRIMARY KEY,
    POST INT NOT NULL,
    AUTHOR INT NOT NULL,
    CONTENT TEXT NOT NULL,
    TIMESTAMP DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT FK_COMMENT_POST
        FOREIGN KEY (POST) REFERENCES POST(POSTID)
        ON DELETE CASCADE,

    CONSTRAINT FK_COMMENT_AUTHOR
        FOREIGN KEY (AUTHOR) REFERENCES USER(USERID)
        ON DELETE CASCADE
);
